### ISSUE TITLE
Raid den boss level

### ISSUE THREAD

**Issue by bob24170** [kwsch/pkNX#152]
I notice that the levels of the boss pokemons in raid dens are random, is there a way to set them at a certain number, say level 60? Thanks.

**Comment by kwsch** [comment]
Distribution raids are at a fixed level, according to the bcat data.
ROM raids are at random ranges, according to the rank (stars) of the den.

Anything is possible, but this kind of code edit is a bit too complex / low value. If someone were to disassemble the relevant routines and provide a patch, then it'd be better handled as a patch rather than a romfs/exefs modification.
