### ISSUE TITLE
[PLA] Index out of bounds exception when trying to edit personal

### ISSUE THREAD

**Issue by Jmc1922** [kwsch/pkNX#275]
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at pkNX.WinForms.PokeDataUI8a.LoadPersonal(IPersonalInfoPLA pkm) in D:\a\1\s\pkNX.WinForms\Subforms\PokeDataUI8a.cs:line 213
   at pkNX.WinForms.PokeDataUI8a.LoadIndex(Int32 index) in D:\a\1\s\pkNX.WinForms\Subforms\PokeDataUI8a.cs:line 178
   at pkNX.WinForms.PokeDataUI8a.UpdateIndex(Object sender, EventArgs e) in D:\a\1\s\pkNX.WinForms\Subforms\PokeDataUI8a.cs:line 168
```

**Comment by Jmc1922** [comment]
I was on the Pokémon editor button and was scrolling through the Pokémon then when I got to kleavor it froze and PKNX was saying he was a normal type and had no data basically then when I got to Ursuline that error message popped up

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JelleInfinity** [comment]
Should be fixed now :)

**Comment by Jmc1922** [comment]
No I dumped the game using updates , it’s been fine but now it doesn’t have any data for Kleavor-enamourus

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JelleInfinity** [comment]
![image](https://user-images.githubusercontent.com/60387522/195018105-b77b2d87-f307-4688-9bc5-1b86a62a2aa6.png)
It does for me. Possibly due to the previous bug, it saved empty data.

You can try to delete the file `arceus\romfs\bin\pml\personal\personal_data_total.perbin`. This is the modded file. Your clean file should then be picked up again, which should contain the original data.
