### ISSUE TITLE
PKNX Issue with Pokemon Violet and Scarlet

### ISSUE THREAD

**Issue by RuinousPrincess** [kwsch/pkNX#292]
For some reason I cannot edit anything. I click on Master Dump to open to a new window, but upon clicking on Personal Stats or Moves, any of the options, a new window won't open period or PKNX sometimes crashes or freezes. I can't get it working period. I'm not sure if it's not compatible with these games yet or it's bugged.

**Comment by kwsch** [comment]
pkNX does not support editing S/V at this time. The main GUI only works for launching `Master Dump`.

We've added logic to dump information from the game files into readable json/tables/text, which is what `Master Dump` opens. Each of those options triggers a dumping operation, not opening another GUI. Some of them are computationally intensive, and lock the GUI while the program calculates and exports to the dump folder.

Due to the romfs having a completely packed trpfs/trpfd, for purposes of layeredfs (minimal file size patches), we can't just overwrite the concatenated data (even if the serialized file data is the same size). The community is working to figure out the best way to sideload content from this game.

**Comment by RuinousPrincess** [comment]
Ah okay. I'll just will have to wait until support is added then before being able to do anything. Wasn't aware it's not supported still. Thanks.

**Comment by Spouik** [comment]
Hello, does pkNX now support SV editing or not ? I can load files but it only shows "Show Field Editors" and "Show Dialog Editors" and when I want to open an editor like common or script, it says "Unknown GameFile provided." https://imgur.com/a/Ac69iD6

**Comment by kwsch** [comment]
> Hello, does pkNX now support SV editing or not ?

No. Editing support has not been added, same as my previous reply to this issue.

**Comment by Spouik** [comment]
Okay, thank you for the reply, have a good day :)

**Comment by duckdoom4** [comment]
Closing this, as keeping an issue open for 'add SV support' seems a bit unnecessary
