### ISSUE TITLE
[Bug] SwSh gets wrong Evolve results in the latest build, but works as intended in previous build.

### ISSUE THREAD

**Issue by XOR-op** [kwsch/pkNX#316]
### What bug I encountered:
Contents from "Evolve" menu are broken after about Dex No.100 in the latest build (20221217.4). However, in previous build (20221205.1), the functionality works as intended. The result looks like the program links evolving info from other wrong pokemon.

### How to reproduce it:
With Sword 1.3.2 with 2DLCs and build 20221217.4, "Evolve" for Eevee is empty, and for Regigigas is Exploud at lvl.40.

**Comment by TheJoshuaRusso** [comment]
How would we go about downloading 20221205? Cause I only see the newest releases on Azure...

**Comment by XOR-op** [comment]
Probably manually build with a commit around the date?

**Comment by observeroftime01** [comment]
This is still an issue in the latest [master](https://github.com/kwsch/pkNX/commit/0a2e7c067469228db8acd4f00ff52c3b3d148807) build for Sw/Sh 1.3.2 unfortunately.

Some more info and observations: 
The last correct evolution is 
`"Krabby - 098 -> Kingler - 099" @ lvl 28`. 
Anything past 100 (Voltorb - 100) has incorrect evolutions. The first "random" bad evolution that appears is 
`"Rhydon - 112 -> Darmanitan 2 - 1012 @ Ice Stone"`, followed by 
`"Horsea - 116 -> Runerigus - 867 @ HitPointsLostInBattle Argument 49"`  (???) and
`"Mr. Mime - 122 -> Exeggutor - 103 @ leaf stone`.
I have been looking for some sort of pattern in the bad evolution data, but I can't seem to find one, so I have no idea where to start looking for the issue here. 

The "Personal" and "Learnset" tab appears unaffected and has the correct info in it, as far as I can tell. The only other oddity I've come across is in the "Raid Reward" editor, where every single "rewards" field has the following in it:

```Unable to cast object of type 'GeneratedVector_4a9ed7339eed7b298a3c9fda278e3eba_GreedyMutable`1[FlatSharp.ArrayInputBuffer]' to type 'System.Collections.Generic.IList`1[pkNX.Structures.FlatBuffers.SWSH.INestHoleReward]'.```

Other than that, there are no other errors or warnings that come up, and for all intents and purposes, the program appears to behave correctly.
